print("Olá turma do Python!")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
nacionalidade: str = ("Indique a sua nacionalidade. ")
print(f"nacionalidade, {nacionalidade}")
